DEBUG = True

SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://root@localhost/deeplab'
SQLALCHEMY_TRACK_MODIFICATIONS = True
SEND_FILE_MAX_AGE_DEFAULT = 0
TOKEN_SECRET = 'secret'
#UPLOAD_FOLDER = './images/'